version: '3.5'
services:
    postgres:
        image: postgres:9.6
        container_name: airflow_postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
            - backend

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        #restart: always
        container_name: airflow_webserver
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
            - SUPERUSER_NAME=${SUPERUSER_NAME}
            - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
            - SUPERUSER_PW=${SUPERUSER_PW}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        networks:
            - backend
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        
networks:
    backend:
        name: airflow_network
